---
- name: Create log director  
  file: path=/var/log/cinder_setup state=directory mode=0666 


- name: test if lvm disk exist
  shell: fdisk -l {{cinder_volume_device}}  
  register: lvm
  ignore_errors: true

- name: test if create lvm again
  stat: path=/var/log/cinder_setup/.cinder_lvm_created
  register: cinder_lvm
  when: lvm.rc == 0  

- name: install lvm
  apt: name={{item}} force=yes
  with_items:
     - lvm2
     - tgt
  when: cinder_lvm.stat.exists ==false
  ignore_errors: true

- name: Create the LVM physical volume
  shell: pvcreate {{cinder_volume_device}}
  when: cinder_lvm.stat.exists ==false
  ignore_errors: true

- name: Create the LVM volume group 
  shell: vgcreate {{cinder_volume_name}} {{cinder_volume_device}} && touch /var/log/cinder_setup/.cinder_lvm_created
  when: cinder_lvm.stat.exists ==false
  ignore_errors: true

- name: copy lvm.conf
  template: src=lvm.conf.j2 dest=/etc/lvm/lvm.conf backup=yes
  ignore_errors: true

- name: install cinder volume
  apt: name=cinder-volume force=yes

- name: copy cinder.conf
  template: src=cinder.conf.j2 dest=/etc/cinder/cinder.conf

- name: restart  cinder-volume service
  service: name=cinder-volume state=restarted 

- name: restart tgt service 
  service: name=tgt state=restarted enabled=yes

  
