---
 
- name: install lvm
  apt: name={{item}} force=yes
  with_items:
     - lvm2
     - cinder-volume
     - tgt

- name: Create the LVM physical volume
  shell: pvcreate {{cinder_volume_device}}
 
- name: Create the LVM volume group 
  shell: vgcreate {{cinder_volume_name}} {{cinder_volume_device}}

- name: copy cinder.conf
  template: src=cinder.conf.j2 dest=/etc/cinder/cinder.conf

- name: restart tgt, cinder-volume service
  service: name={{item}} state=restarted enabled=yes
  with_items:
     - tgt
     - cinder-volume
