---
- name: Deploy Contoller
  hosts: controller
  gather_facts: no
  environment: {{openstack_environment}}
  roles:
    - prepare-controller
    - keystone
    - glance
    - nova-controller
    - neutron-controller
    - horizon
    - cinder-controller
    - heat
