---
- hosts: controller
  remote_user: root
  gather_facts: False
  environment: "{{ openstack_environment }}"
   
  pre_tasks:
    - name: Test keystone
      stat: path=/var/log/keystone_installation
      register: ks_state

  roles:

    - role: prepare-controller
    - role: keystone
      when: ks_state.stat.exists ==false
    - role: glance
    - role: heat
