---
# tasks file for neutron-copute

- name: echo 'net.ipv4.conf.default.rp_filter=0' >> /etc/sysctl.conf 
  sysctl:
    name: net.ipv4.conf.default.rp_filter
    value: 0
    sysctl_set: yes
    state: present
    reload: yes
  sudo: True



- name: echo 'net.ipv4.conf.all.rp_filter=0' >> /etc/sysctl.conf 
  sysctl:
    name: net.ipv4.conf.all.rp_filter
    value: 0
    sysctl_set: yes
    state: present
    reload: yes
  sudo: True

- name:
  modprobe:
    name: br_netfilter
    state: present

- name: echo 'net.bridge.bridge-nf-call-iptables=1' >> /etc/sysctl.conf 
  sysctl:
    name: net.bridge.bridge-nf-call-iptables
    value: 1
    sysctl_set: yes
    state: present
    reload: yes


- name: echo 'net.bridge.bridge-nf-call-ip6tables=1' >> /etc/sysctl.conf 
  sysctl:
    name: net.bridge.bridge-nf-call-ip6tables
    value: 1
    sysctl_set: yes
    state: present
    reload: yes



- name: install neutron-common neutron-plugin-ml2 neutron-plugin-linuxbridge-agent 
  apt: name={{item}}  update_cache=yes cache_valid_time=3600
  with_items:
    - neutron-common 
    - neutron-plugin-ml2 
    - neutron-plugin-linuxbridge-agent 

- name: copy /etc/neutron/neutron.conf 
  template:
    src: neutron.conf.j2
    dest: /etc/neutron/neutron.conf 
    group: neutron
    backup: yes

- name: template /etc/neutron/plugins/ml2/ml2_conf.ini
  template:
    src: ml2_conf.ini.j2
    dest: /etc/neutron/plugins/ml2/ml2_conf.ini
    group: neutron
    backup: yes


- name: ln -s /etc/neutron/plugins/ml2/ml2_conf.ini /etc/neutron/plugin.ini 
  file: 
    src: /etc/neutron/plugins/ml2/ml2_conf.ini
    dest: /etc/neutron/plugin.ini
    state: link


- name: template /etc/nova/nova.conf  
  template:
    src: ../../../common-templates/compute-nova.conf
    dest: /etc/nova/nova.conf
    group: nova
    backup: yes


- name: Get overlay network IP
  shell: >
    ifconfig | awk -F "[: ]+" '/inet addr:/ { if ($4 != "127.0.0.1") print $4 }' | grep {{os_neutron_overlay_network_starts_with}}
  register: overlay_network


- name: test overlay_network
  debug: msg={{overlay_network}}

- name: Tempalte /etc/neutron/plugins/ml2/linuxbridge_agent.ini 
  template:
    src:  linuxbridge_agent.ini.j2
    dest: /etc/neutron/plugins/ml2/linuxbridge_agent.ini 
    backup: yes

- name: Restart & enable nova-compute nova-api-metadata neutron-linuxbridge-agent
  service: name={{item}} state=restarted enabled=yes
  with_items:
    - nova-compute 
    #- nova-api-metadata 
    - neutron-linuxbridge-agent 

