---
- name: Install nova-compute
  apt: name=nova-compute state=present
- name: Modify /etc/nova/nova.conf
  template: src=nova.conf dest=/etc/nova/nova.conf
- name: Test if the compute node supports hardware acceleration
  shell: egrep -c '(vmx|svm)' /proc/cpuinfo
  register: hardware_acceleration
  ignore_errors: yes
  register: hardware_acceleration
- name: Modify /etc/nova/nova-compute.conf
  template: src=nova-compute.conf dest=/etc/nova/nova-compute.conf
- name: Restart nova-compute
  service: name=nova-compute state=restarted

