---
# handlers file for environment
- name: restart chrony
  service: name=chrony state=restarted
- name: restart mariadb
  service: name=mysql state=restarted
- name: restart memcached
  service: name=memcached state=restarted
