---
  
   - name: create cinder mysql db
     mysql_db: name=cinder state=present
   
   - name: create cinder db user1
     mysql_user: name=cinder password="{{ cinder_dbpass }}" priv=cinder.*:ALL host=% state=present

   - name: create cinder db user2
     mysql_user: name=cinder password="{{ cinder_dbpass }}" priv=cinder.*:ALL host=localhost state=present

   - name: create cinder user
     raw: > 
          source /root/admin-openrc;
          openstack user create --domain default --password {{ cinder_userpass }} cinder
   
   - name: add cinder user to admin roles
     raw: >
         source /root/admin-openrc; 
         openstack role add --project service --user cinder admin

   - name: Create the cinder and cinderv2 service
     raw: >
         source /root/admin-openrc;
         openstack service create --name cinder --description "OpenStack Block Storage" volume;
         openstack service create --name cinderv2  --description "OpenStack Block Storage" volumev2
   

   - name: create cinder endpoint
     raw: >
         source /root/admin-openrc;
         openstack endpoint create --region RegionOne volume public http://controller:8776/v1/%\(tenant_id\)s;
         openstack endpoint create --region RegionOne volume internal http://controller:8776/v1/%\(tenant_id\)s;
         openstack endpoint create --region RegionOne volume admin http://controller:8776/v1/%\(tenant_id\)s;
         openstack endpoint create --region RegionOne volumev2 public http://controller:8776/v2/%\(tenant_id\)s;
         openstack endpoint create --region RegionOne volumev2 internal http://controller:8776/v2/%\(tenant_id\)s;
         openstack endpoint create --region RegionOne volumev2 admin http://controller:8776/v2/%\(tenant_id\)s
     

   - name: install cinder package
     shell: apt install -y cinder-api cinder-scheduler


   - name: copy cinder.conf 
     template: src=cinder.conf.j2 dest=/etc/cinder/cinder.conf

   - name: Populate  cinder database
     shell: su -s /bin/sh -c "cinder-manage db sync" cinder


   - name: modify nova.conf
     shell: >
      [ `grep -e '^os_region_name' /etc/nova/nova.conf|wc -l` -eq 1 ] || sed -i '$a [cinder]\nos_region_name = RegionOne' /etc/nova/nova.conf

   - name: restart cinder nova-api service
     service : name={{item}} state=restarted 
     with_items:
       - nova-api 
       - cinder-scheduler
       - cinder-api
