---
- name: install python
  raw: >
       apt-get -y update ;
       apt-get -y install python
- name: install debian-archive-keyring
  apt: name=debian-archive-keyring state=present
- name: install chrony
  apt: name=chrony state=present
- name: modify /etc/chrony/chrony.conf
  template: src=chrony.conf dest=/etc/chrony/chrony.conf
  register: restart_chrony
- name: install software-properties-common
  apt: name=software-properties-common state=present
- name: add "cloud-archive:{{openstack_version}}" repository
#  apt_repository: repo='deb http://ubuntu-cloud.archive.canonical.com/ubuntu xenial-updates/{{openstack_version}} main' state=present filename='cloudarchive-{{openstack_version}}'
  shell:   test -e /etc/apt/sources.list.d/cloudarchive-newton.list || (add-apt-repository cloud-archive:newton -y)
- name: upgrade all packages
  apt: upgrade=dist force=yes
- name: install python-openstackclient
  apt: name=python-openstackclient state=present force=yes
- name: install mariadb-server python-pymysql rabbitmq-server memcached python-memcache apache2   
  apt: name="{{item}}" state=present
  with_items:
    - python-pip
    - libmysqlclient-dev
    - mariadb-server
    - python-pymysql
    - rabbitmq-server
    - memcached
    - python-memcache
    - apache2
- name: upgrade pip
  shell: pip install --upgrade pip
- name: Install the Python MySQLB module
  pip: name=MySQL-python
- name: Sets mysql's root password 
  mysql_user: user=root password={{mysql_root_password}} host="{{item}}"
  with_items:
    - "localhost"
    - "%"
- name: Removes all anonymous user accounts
  mysql_user: name='' host_all=yes state=absent
- name: Remove test database
  mysql_db: name=test state=absent
- name: add rabbitmq user and config privileges
  rabbitmq_user:
    user: "{{rabbitmq_admin}}"
    password: "{{rabbitmq_admin_password}}"
    vhost: /
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    state: present
- name: modify /etc/mysql/mariadb.conf.d/99-openstack.cnf
  template: src=99-openstack.cnf dest=/etc/mysql/mariadb.conf.d/99-openstack.cnf
  register: restart_mariadb
- name: modify /etc/memcached.conf
  template: src=memcached.conf dest=/etc/memcached.conf
  register: restart_memcached
- name: restart chrony
  service: name=chrony state=restarted
  when: restart_chrony|changed
- name: restart mariadb
  service: name=mysql state=restarted
  when: restart_mariadb|changed
- name: restart memcached
  service: name=memcached state=restarted
  when: restart_memcached|changed
