---
- name: Update the repository cache
  apt: update_cache=yes
- name: install debian-archive-keyring
  apt: name=debian-archive-keyring state=present
- name: install chrony
  apt: name=chrony state=present
- name: modify /etc/chrony/chrony.conf
  template: src=chrony.conf dest=/etc/chrony/chrony.conf
  notify:
    - restart chrony
  tags:
    - chrony
- name: install software-properties-common
  apt: name=software-properties-common state=present
- name: add "cloud-archive:{{openstack_version}}" repository
  apt_repository: repo='deb http://ubuntu-cloud.archive.canonical.com/ubuntu xenial-updates/{{openstack_version}} main' state=present filename='cloudarchive-{{openstack_version}}'
- name: upgrade all packages
  apt: upgrade=dist force=yes
- name: install python-openstackclient
  apt: name=python-openstackclient state=present force=yes
- name: install mariadb-server python-pymysql rabbitmq-server memcached python-memcache apache2   
  apt: name="{{item}}" state=present
  with_items:
    - mariadb-server
    - python-pymysql
    - rabbitmq-server
    - memcached
    - python-memcache
    - apache2
- name: Install the Python MySQLB module   
  pip: name=MySQL-python
- name: add rabbitmq user and config privileges
  rabbitmq_user:
    user: "{{rabbitmq_admin}}"
    password: "{{rabbitmq_admin_password}}"
    vhost: /
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    state: present
- name: modify /etc/mysql/mariadb.conf.d/99-openstack.cnf
  template: src=99-openstack.cnf dest=/etc/mysql/mariadb.conf.d/99-openstack.cnf
  notify: 
    - restart mariadb
- name: modify /etc/memcached.conf
  template: src=memcached.conf dest=/etc/memcached.conf
  notify: restart memcached
