---
  - name: install dashboard package
    apt: pkg=openstack-dashboard force=yes 
 
  - name: local setting file exist
    stat: path=/etc/openstack-dashboard/local_settings.py
    register: fileexist
   
  
  - name: file dashboard file 
    template: src=local_settings.py.j2 dest=/etc/openstack-dashboard/local_settings.py
    notify: restart apache2
    when: fileexist.stat.exists == false
