---
  - name: install dashboard package
    command:  apt install -y openstack-dashboard     
  
  - name: file dashboard file 
    copy: src=local_settings.py dest=/etc/openstack-dashboard/local_settings.py
    notify: restart apache2

