---
  - name: install dashboard package
    apt: pkg=openstack-dashboard force=yes 
 
    
  - name: file dashboard file 
    template: src=local_settings.py dest=/etc/openstack-dashboard/local_settings.py
    notify: restart apache2
