---
# tasks file for neutron-network
- name: Install install neutron-server neutron-plugin-ml2 python-neutronclient 
  apt: name={{item}} update_cache=yes cache_valid_time=3600
  with_items:
    - "python-neutronclient"


- name: echo 'net.ipv4.ip_forward=1' >> /etc/sysctl.conf 
  sysctl:
    name: net.ipv4.ip_forward
    value: 1
    sysctl_set: yes
    state: present
    reload: yes


- name: echo 'net.ipv4.conf.default.rp_filter=0' >> /etc/sysctl.conf 
  sysctl:
    name: net.ipv4.conf.default.rp_filter
    value: 0
    sysctl_set: yes
    state: present
    reload: yes



- name: echo 'net.ipv4.conf.all.rp_filter=0' >> /etc/sysctl.conf 
  sysctl:
    name: net.ipv4.conf.all.rp_filter
    value: 0
    sysctl_set: yes
    state: present
    reload: yes


- name: install neutron computnents
  apt: name={{item}}  update_cache=yes cache_valid_time=3600
  with_items:
    - neutron-plugin-ml2
    - neutron-plugin-linuxbridge-agent
    - neutron-l3-agent
    - neutron-dhcp-agent
    - neutron-metadata-agent
    - python-neutronclient

- name: copy /etc/neutron/neutron.conf 
  template: 
    src: neutron.conf.j2
    dest: /etc/neutron/neutron.conf
    group: neutron

- name: copy /etc/neutron/l3_agent.ini 
  copy:
    src: l3_agent.ini 
    dest: /etc/neutron/l3_agent.ini
    group: neutron

- name: copy  /etc/neutron/dhcp_agent.ini 
  copy:
    src: dhcp_agent.ini
    dest: /etc/neutron/dhcp_agent.ini
    group: neutron

- name: copy /etc/neutron/metadata_agent.ini
  template:
    src: metadata_agent.ini.j2
    dest: /etc/neutron/metadata_agent.in
    group: neutron


- name: copy /etc/neutron/plugins/ml2/ml2_conf.ini 
  copy:
    src: ml2_conf.ini
    dest: /etc/neutron/plugins/ml2/ml2_conf.ini
    group: neutron


- name: ln -s /etc/neutron/plugins/ml2/ml2_conf.ini /etc/neutron/plugin.ini 
  file: 
    src: /etc/neutron/plugins/ml2/ml2_conf.ini
    dest: /etc/neutron/plugin.ini
    state: link

- name: restart service; l3-agent dhcp-agent metadata-agent linuxbridge-agent
  service: "name={{item}} state=restarted"
  with_items:
    - "neutron-l3-agent"
    - "neutron-dhcp-agent"
    - "neutron-metadata-agent"
    - "neutron-linuxbridge-agent"
